<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<jsp:include page="layout/nav-bar.jsp" />
<jsp:include page="layout/header.jsp" />
<link
	href="assets/plugins/custom/datatables/datatables.bundle.css?v=7.0.5"
	rel="stylesheet" type="text/css" />
<!--begin::Content-->
<div class="content d-flex flex-column flex-column-fluid"
	id="kt_content">
	<!--begin::Subheader-->
	<div class="subheader py-2 py-lg-4 subheader-solid" id="kt_subheader">
		<div
			class="container-fluid d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">
			<!--begin::Info-->
			<div class="d-flex align-items-center flex-wrap mr-2">
				<!--begin::Page Title-->
				<h5 class="text-dark font-weight-bold mt-2 mb-2 mr-5">Client</h5>
				<!--end::Page Title-->
				<!--begin::Actions-->
				<div
					class="subheader-separator subheader-separator-ver mt-2 mb-2 mr-4 bg-gray-200"></div>
			</div>
			<div class="d-flex align-items-center">
				<button type="button"
					class="btn btn-light-warning font-weight-bolder btn-sm"
					data-toggle="modal" data-target="#newClientModal">Add New</button>
				<!--end::Actions-->
			</div>
			<!--end::Info-->
		</div>
	</div>
	<!--end::Subheader-->
	<div class="d-flex flex-column-fluid">
		<!--begin::Container-->
		<div class="container">
			<div class="card card-custom">
				<div class="card-body">
					<table class="table table-bordered table-hover table-checkable"
						style="margin-top: 13px !important" id="client_dataTable">
						<thead>
							<tr>
								<th>Client Name</th>
								<th>Mobile Number</th>
								<th>Email ID</th>
								<th>Revenue Generated</th>
								<th>Actions</th>
							</tr>
						</thead>
					</table>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- Modal-->
<div class="modal fade" id="newClientModal" data-backdrop="static"
	tabindex="-1" role="dialog" aria-labelledby="staticBackdrop"
	aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h3 id="newClientModalLabel">New Client</h3>
				<div id="clientExists"
					style="display: none; color: red; text-align: center"></div>
				<button type="button" class="close" data-dismiss="modal"
					onclick="clearNewClientForm();" aria-label="Close">
					<i aria-hidden="true" class="ki ki-close"></i>
				</button>
			</div>
			<div class="modal-body">
				<jsp:include page="../views/forms/new-client-form.jsp" />
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-light-primary"
					onclick="clearNewClientForm();" data-dismiss="modal">Close</button>
				<button type="button" id="submitNewClientForm"
					class="btn btn-primary mr-2">Save changes</button>
			</div>
		</div>
	</div>
</div>
<!--End Modal-->
<!-- Modal-->
<div class="modal fade" id="editClientModal" data-backdrop="static"
	tabindex="-1" role="dialog" aria-labelledby="staticBackdrop"
	aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h3 id="editClientModalLabel">Edit Client</h3>
				<div id="editClientExists"
					style="display: none; color: red; text-align: center"></div>
			</div>
			<div class="modal-body">
				<jsp:include page="../views/forms/edit-client-form.jsp" />
			</div>
			<div class="modal-footer">
				<button type="button" onclick="clearEditClientForm();"
					class="btn btn-light-primary font-weight-bold" data-dismiss="modal">Close</button>
				<button type="button" onclick="submitEditForm()"
					class="btn btn-primary mr-2">Save changes</button>
			</div>
		</div>
	</div>
</div>
<!--End Modal-->
<!-- Modal-->
<div class="modal fade" id="clientDetailsModal" data-backdrop="static"
	tabindex="-1" role="dialog" aria-labelledby="staticBackdrop"
	aria-hidden="true">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h3 id="clientDetailsModalLabel">Client Details</h3>
			</div>
			<div class="modal-body">
				<form class="form">
					<div class="form-group row">
						<div class="col-lg-6">
							<label>Total Visits:</label>
							<div class="input-group">
								<input id="totalVisits" type="text" class="form-control"
									readonly />
							</div>
							<span id="clientLoyaltyPoints_span" class="form-text text-muted">Client's
								Total Visit's</span>
						</div>
						<div class="col-lg-6">
							<label>Revenue Generated:</label>
							<div class="input-group">
								<div class="input-group-prepend">
									<span class="input-group-text">&#8377;</span>
								</div>
								<input id="clientDetailsRevenueGenerated" type="text"
									class="form-control" readonly />
							</div>
							<span id="clientDetailsRevenueGenerated_span"
								class="form-text text-muted"> Revenue generated by client</span>
						</div>
					</div>
					<div class="form-group row">
						<div class="col-lg-6">
							<label>Last Visited:</label>
							<div class="input-group date">
								<div class="input-group-prepend">
									<span class="input-group-text"><i class="la la-calendar"></i></span>
								</div>
								<input type="text" class="form-control" readonly="readonly"
									id="clientDetailsLastVisited" disabled />
							</div>
							<span class="form-text text-muted ">Client's last visited
								date</span>
						</div>
						<div class="col-lg-6">
							<label>Client Created Date:</label>
							<div class="input-group date">
								<div class="input-group-prepend">
									<span class="input-group-text"><i class="la la-calendar"></i></span>
								</div>
								<input type="text" class="form-control" readonly="readonly"
									id="clientDetailsCreatedDate" disabled />
							</div>
							<span class="form-text text-muted ">Client Created date</span>
						</div>
					</div>
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-light-primary font-weight-bold"
					data-dismiss="modal">Close</button>
			</div>
		</div>
	</div>
</div>
<!--End Modal-->
<style type="text/css">
span.error {
	color: red;
}

span.select2 {
	width: 100% !important;
}
</style>
<script>
	var HOST_URL = "${pageContext.request.contextPath}"
</script>
<script type='text/javascript'>
	document.addEventListener('DOMContentLoaded', function(e) {
		const clientForm = document.getElementById('clientForm');
		const fv = FormValidation.formValidation(clientForm, {
			fields : {
				fullName : {
					validators : {
						notEmpty : {
							message : 'please enter client\'s full name'
						}
					}
				},
				mobileNumber : {
					validators : {
						notEmpty : {
							message : 'please enter client\'s mobile number'
						},
						regexp : {
							regexp : /^[0-9]{10,10}$/,
							message : 'please enter a valid mobile number (10 digits).'									
						}
					}
				}
			},
			plugins : {
				trigger : new FormValidation.plugins.Trigger(),
				bootstrap : new FormValidation.plugins.Bootstrap(),
				submitButton : new FormValidation.plugins.SubmitButton(),
			//defaultSubmit : new FormValidation.plugins.DefaultSubmit()
			// Uncomment this line to enable normal button submit after form validation												
			}
		});
		$('#submitNewClientForm').on('click', function(e) {
			e.preventDefault();
			fv.validate().then(function(status) {
				var invalid = false;
				if (status == 'Valid') {
					/* 																	invalid = checkIfAllEntriesAreValid();
					 if (invalid) {
					 swal
					 .fire(
					 {
					 text : "Sorry, looks like there are some errors detected, please make sure all services and staff are selected and try again.",
					 icon : "error",
					 buttonsStyling : false,
					 confirmButtonText : "Ok, got it!",
					 customClass : {
					 confirmButton : "btn font-weight-bold btn-light-primary"
					 }
					 })
					 .then(
					 function() {
					 KTUtil
					 .scrollTop();
					 });
					 } else { */
					document.getElementById("clientForm").action = "client";
					document.getElementById("clientForm").submit();
					//}
				} else {
					KTUtil.scrollTop();

				}
			});
		});
	});
	$('#loading-spinner').hide();
	jQuery(document).ready(function() {
		var clientToAdd = '${newClient}';
		if (clientToAdd.length > 0) {
			$('#newClientModal').modal();
			$('#fullName').val(clientToAdd);
		}
		var clientToShow = '${showClientDetails}';
		if (clientToShow.length > 0) {
			fetchClientDetails(clientToShow);
		}
		var doesExist = '${clientExists}';
		var doesEditExist = '${editClientExists}';
		var data = '${editClientForm}';
		if (doesExist.length > 2) {
			$('#clientExists').html(doesExist);
			$('#clientExists').show();
			$('#newClientModal').modal();
		}
		if (doesEditExist.length > 2) {
			$('#editClientExists').html(doesEditExist);
			$('#editClientExists').show();
			$('#editClientModal').modal();
		}
	});
</script>
<script type="text/javascript"
	src="<c:url value="/assets/js/utilities/push-divs.js" />"></script>
<script type="text/javascript"
	src="<c:url value="/assets/plugins/custom/datatables/datatables.bundle.js?v=7.0.5"/>"></script>
<script type="text/javascript"
	src="<c:url value="/assets/js/utilities/datePicker.js" />"></script>
<script type="text/javascript"
	src="<c:url value="/assets/js/utilities/select2.js" />"></script>
<script type="text/javascript"
	src="<c:url value="/assets/js/pages/client/client.js" />"></script>